# Generated by Django 4.2.29 on 2026-03-24 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("super_user", "Super User"),
                            ("super_workspace_user", "Super Workspace User"),
                            ("user", "User"),
                        ],
                        db_index=True,
                        default="user",
                        max_length=20,
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("avatar", models.URLField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("job_title", models.CharField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status_message",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "last_seen",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=80)),
                ("description", models.TextField(blank=True, null=True)),
                ("topic", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("direct", "Direct"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dm_with",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dm_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "channels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChannelSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("section_type", models.CharField(default="custom", max_length=20)),
                ("is_collapsed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "channel_sections",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomEmoji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Emoji shortcode without colons, e.g., 'party-parrot'",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        help_text="Emoji image file (PNG, GIF, JPG)",
                        upload_to="custom_emojis/%Y/%m/",
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "alias_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aliases",
                        to="core.customemoji",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_emojis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custom_emojis",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("is_edited", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.channel",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dm_recipient",
                    models.ForeignKey(
                        blank=True,
                        help_text="For direct messages, the recipient user",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this is a reply, the parent message",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="core.message",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.URLField(blank=True, null=True)),
                ("is_private", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("workspace_url", models.URLField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workspaces",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UnreadCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("count", models.PositiveIntegerField(default=0)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unread_counts",
                        to="core.channel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unread_counts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "unread_counts",
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("all_notifications_enabled", models.BooleanField(default=True)),
                ("desktop_notifications", models.BooleanField(default=True)),
                ("mobile_notifications", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sound_enabled", models.BooleanField(default=True)),
                ("mention_notifications", models.BooleanField(default=True)),
                ("dm_notifications", models.BooleanField(default=True)),
                (
                    "thread_notifications",
                    models.CharField(
                        choices=[
                            ("all", "All messages"),
                            ("mentions", "Only @mentions"),
                            ("none", "Nothing"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("reaction_notifications", models.BooleanField(default=True)),
                ("keyword_notifications", models.BooleanField(default=True)),
                (
                    "channel_mention_notifications",
                    models.CharField(
                        choices=[
                            ("all", "All messages"),
                            ("mentions", "Only @mentions"),
                            ("none", "Nothing"),
                        ],
                        default="mentions",
                        max_length=20,
                    ),
                ),
                ("dnd_enabled", models.BooleanField(default=False)),
                (
                    "dnd_start_time",
                    models.TimeField(blank=True, default="22:00", null=True),
                ),
                (
                    "dnd_end_time",
                    models.TimeField(blank=True, default="08:00", null=True),
                ),
                (
                    "email_digest_frequency",
                    models.CharField(
                        choices=[
                            ("off", "Off"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="off",
                        max_length=20,
                    ),
                ),
                (
                    "muted_channels",
                    models.ManyToManyField(
                        blank=True, related_name="muted_by", to="core.channel"
                    ),
                ),
                (
                    "muted_workspaces",
                    models.ManyToManyField(
                        blank=True, related_name="muted_by", to="core.workspace"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_settings",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("mention", "Mention"),
                            ("dm", "Direct Message"),
                            ("thread_reply", "Thread Reply"),
                            ("reaction", "Reaction"),
                            ("channel_message", "Channel Message"),
                            ("keyword_alert", "Keyword Alert"),
                            ("channel_mention", "@channel"),
                            ("here_mention", "@here"),
                            ("everyone_mention", "@everyone"),
                            ("workspace_invite", "Workspace Invite"),
                            ("channel_invite", "Channel Invite"),
                        ],
                        default="mention",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, max_length=500)),
                ("link", models.CharField(blank=True, max_length=500)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.channel",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.message",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggered_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("emoji", models.CharField(max_length=50)),
                (
                    "custom_emoji",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reactions",
                        to="core.customemoji",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="core.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "message_reactions",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageEditHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "old_content",
                    models.TextField(help_text="The content before this edit"),
                ),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_history",
                        to="core.message",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Message edit histories",
                "db_table": "message_edit_history",
                "ordering": ["-edited_at"],
            },
        ),
        migrations.CreateModel(
            name="KeywordAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("keyword", models.CharField(max_length=100)),
                ("notify_on_match", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_alerts",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "keyword_alerts",
            },
        ),
        migrations.AddField(
            model_name="customemoji",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_emojis",
                to="core.workspace",
            ),
        ),
        migrations.CreateModel(
            name="ChannelSectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_items",
                        to="core.channel",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.channelsection",
                    ),
                ),
            ],
            options={
                "db_table": "channel_section_items",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="channelsection",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_sections",
                to="core.workspace",
            ),
        ),
        migrations.CreateModel(
            name="ChannelMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mention_type",
                    models.CharField(
                        choices=[
                            ("channel", "@channel"),
                            ("here", "@here"),
                            ("everyone", "@everyone"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_mentions",
                        to="core.message",
                    ),
                ),
                (
                    "notified_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="channel_mention_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "channel_mentions",
            },
        ),
        migrations.CreateModel(
            name="ChannelMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("member", "Member"),
                            ("guest", "Guest"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("is_muted", models.BooleanField(default=False)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.channel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "channel_memberships",
                "ordering": ["channel", "user"],
            },
        ),
        migrations.AddField(
            model_name="channel",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="core.workspace",
            ),
        ),
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("guest", "Guest"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_memberships",
                "ordering": ["workspace", "user"],
                "indexes": [
                    models.Index(
                        fields=["user", "workspace"],
                        name="workspace_m_user_id_dbc29d_idx",
                    ),
                    models.Index(fields=["role"], name="workspace_m_role_8f1d56_idx"),
                ],
                "unique_together": {("user", "workspace")},
            },
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(fields=["name"], name="workspaces_name_f0081f_idx"),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["is_active"], name="workspaces_is_acti_88a65d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(fields=["owner"], name="workspaces_owner_i_04111b_idx"),
        ),
        migrations.AddIndex(
            model_name="unreadcount",
            index=models.Index(
                fields=["user", "count"], name="unread_coun_user_id_b8015e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="unreadcount",
            unique_together={("user", "channel")},
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="notificatio_user_id_a4dd5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "created_at"], name="notificatio_user_id_7336fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type"], name="notificatio_notific_19df93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(
                fields=["message", "emoji"], name="message_rea_message_7f9ef3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(fields=["user"], name="message_rea_user_id_565363_idx"),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(
                fields=["created_at"], name="message_rea_created_f24d92_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagereaction",
            unique_together={("message", "user", "emoji")},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["channel", "created_at"], name="messages_channel_68995e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "created_at"], name="messages_sender__bf8b1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["parent_message"], name="messages_parent__8cda5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["dm_recipient"], name="messages_dm_reci_a70466_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="keywordalert",
            index=models.Index(
                fields=["user", "keyword"], name="keyword_ale_user_id_046140_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="keywordalert",
            unique_together={("user", "keyword", "workspace")},
        ),
        migrations.AddIndex(
            model_name="customemoji",
            index=models.Index(
                fields=["workspace", "name"], name="custom_emoj_workspa_9cc522_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customemoji",
            index=models.Index(
                fields=["created_by"], name="custom_emoj_created_d2cbcd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customemoji",
            unique_together={("workspace", "name")},
        ),
        migrations.AddIndex(
            model_name="channelsectionitem",
            index=models.Index(
                fields=["section", "order"], name="channel_sec_section_358bd0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="channelsectionitem",
            unique_together={("section", "channel")},
        ),
        migrations.AddIndex(
            model_name="channelsection",
            index=models.Index(
                fields=["user", "workspace"], name="channel_sec_user_id_71cea1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channelsection",
            index=models.Index(fields=["order"], name="channel_sec_order_3b2d71_idx"),
        ),
        migrations.AddIndex(
            model_name="channelsection",
            index=models.Index(
                fields=["section_type"], name="channel_sec_section_350fe2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="channelsection",
            unique_together={("user", "workspace", "name")},
        ),
        migrations.AddIndex(
            model_name="channelmembership",
            index=models.Index(
                fields=["user", "channel"], name="channel_mem_user_id_b7bb55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channelmembership",
            index=models.Index(fields=["role"], name="channel_mem_role_85c56a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="channelmembership",
            unique_together={("user", "channel")},
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(fields=["name"], name="channels_name_0d7dd8_idx"),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(
                fields=["workspace"], name="channels_workspa_b3a1d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(
                fields=["channel_type"], name="channels_channel_2bceca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(
                fields=["is_active"], name="channels_is_acti_068c4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_type"], name="users_user_ty_578f8f_idx"),
        ),
    ]
