# Generated by Django 4.2.29 on 2026-03-23 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=80)),
                ("description", models.TextField(blank=True, null=True)),
                ("topic", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("direct", "Direct"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dm_with",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dm_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "channels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.URLField(blank=True, null=True)),
                ("is_private", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("workspace_url", models.URLField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChannelMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("member", "Member"),
                            ("guest", "Guest"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("is_muted", models.BooleanField(default=False)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.channel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "channel_memberships",
                "ordering": ["channel", "user"],
            },
        ),
        migrations.AddField(
            model_name="channel",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="core.group",
            ),
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("guest", "Guest"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "group_memberships",
                "ordering": ["group", "user"],
                "indexes": [
                    models.Index(
                        fields=["user", "group"], name="group_membe_user_id_090956_idx"
                    ),
                    models.Index(fields=["role"], name="group_membe_role_ae792e_idx"),
                ],
                "unique_together": {("user", "group")},
            },
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["name"], name="groups_name_2de3f0_idx"),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["is_active"], name="groups_is_acti_c63b73_idx"),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["owner"], name="groups_owner_i_aea863_idx"),
        ),
        migrations.AddIndex(
            model_name="channelmembership",
            index=models.Index(
                fields=["user", "channel"], name="channel_mem_user_id_b7bb55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channelmembership",
            index=models.Index(fields=["role"], name="channel_mem_role_85c56a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="channelmembership",
            unique_together={("user", "channel")},
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(fields=["name"], name="channels_name_0d7dd8_idx"),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(fields=["group"], name="channels_group_i_f6e6d2_idx"),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(
                fields=["channel_type"], name="channels_channel_2bceca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(
                fields=["is_active"], name="channels_is_acti_068c4a_idx"
            ),
        ),
    ]
